added Works Section and work cards in this commit
Abdulwhbhussain/Microverse_portfolio_project pull request #2
Opened 2023-03-23 16:29 UTC by Abdulwhbhussain

Add these Changes and Updates to the Project:

1. Works Section
2. Work Cards
3. Buttons

2023-03-23 21:09 UTC, hiromataba requested changes
Hi @Abdulwhbhussain     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 21:09 UTC, hiromataba commented on index.html
> +                <div class="snapshoot-container">
- [ ] Please check the original design as suggested in the below [video](https://youtu.be/jiIed23OPMA) recorded for goo understanding 😉

2023-03-23 22:54 UTC, Abdulwhbhussain commented on style.css
> +  gap: 88px;
ok! i implemented it.

2023-03-23 22:54 UTC, Abdulwhbhussain commented on index.html
> +                    </div>
ok.

2023-03-24 03:58 UTC, LionRouge1 approved these changes
Hi @Abdulwhbhussain , 

# STATUS: APPROVED! 🥇 💯 
- Your portfolio looks almost identic to Figma's design :+1: 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-03-24 09:36 UTC, merged